micronaut:
  application:
    name: cms
  security:
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${GENERATOR_SECRET:}
  endpoints:
    logout:
      get-allowed: true
    login:
      enabled: true


login:
  google:
    client-id: ${CLIENT_ID:}
    client-secret: ${CLIENT_SECRET:}



#    endpoints:
#      logout:
#        get-allowed: true
#      login:
#        enabled: true
datasources:
  default:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lomibao_cms_local}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    #schema-generate: CREATE_DROP
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true